name: flutter_qr_generation_example_app
description: "A new Flutter example app with firebase authentication to generate qr"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  get: ^4.6.6
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
