// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvSNGavCgv0idSEGcOcDBz3kbfsF6vubk',
    appId: '1:632210821382:web:e2f1f4cc97a5254ad68e87',
    messagingSenderId: '632210821382',
    projectId: 'personal-db-813c8',
    authDomain: 'personal-db-813c8.firebaseapp.com',
    databaseURL: 'https://personal-db-813c8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-db-813c8.appspot.com',
    measurementId: 'G-SSECXN5P8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8dtS7MxcMjxOqK1dE48DmxZ2wS1w2l78',
    appId: '1:632210821382:android:2af48ca57a53e649d68e87',
    messagingSenderId: '632210821382',
    projectId: 'personal-db-813c8',
    databaseURL: 'https://personal-db-813c8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-db-813c8.appspot.com',
  );
}
